linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - revive

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - private
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: exported
        disabled: true
      - name: receiver-naming
        disabled: true
