version: 1

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - revive
    - shadow

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - private
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104
  misspell:
    locale: US
